package com.vie.mit.common.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

@Immutable
data class AppColors(
    val primary: Color,
    val onPrimary: Color,
    val primaryContainer: Color,
    val onPrimaryContainer: Color,
    val inversePrimary: Color,
    val secondary: Color,
    val onSecondary: Color,
    val secondaryContainer: Color,
    val onSecondaryContainer: Color,
    val tertiary: Color,
    val onTertiary: Color,
    val tertiaryContainer: Color,
    val onTertiaryContainer: Color,
    val background: Color,
    val onBackground: Color,
    val surface: Color,
    val onSurface: Color,
    val surfaceVariant: Color,
    val onSurfaceVariant: Color,
    val surfaceTint: Color,
    val inverseSurface: Color,
    val inverseOnSurface: Color,
    val error: Color,
    val onError: Color,
    val errorContainer: Color,
    val onErrorContainer: Color,
    val outline: Color,
    val outlineVariant: Color,
    val scrim: Color,
    val surfaceDim: Color,
    val surfaceBright: Color,
    val surfaceContainerLowest: Color,
    val surfaceContainerLow: Color,
    val surfaceContainer: Color,
    val surfaceContainerHigh: Color,
    val surfaceContainerHighest: Color,
    // Custom colors
    val success: Color,
    val isLight: Boolean,
    //PhucTH
    val primaryText:Color,
    val secondaryText:Color,
    val disabledColor:Color,

    val primaryButtonBackground:Color

    )

fun lightAppColors(): AppColors = AppColors(

    inversePrimary = md_theme_light_inversePrimary,
    //secondary: Màu để phân biệt với primary kiểu
    secondary = md_theme_light_secondary,
    onSecondary = md_theme_light_onSecondary,
    secondaryContainer = md_theme_light_secondaryContainer,
    onSecondaryContainer = md_theme_light_onSecondaryContainer,
    tertiary = md_theme_light_tertiary,
    onTertiary = md_theme_light_onTertiary,
    tertiaryContainer = md_theme_light_tertiaryContainer,
    onTertiaryContainer = md_theme_light_onTertiaryContainer,
    //Surface: màu nền của màn hình
    surface = md_theme_light_surface,
    onSurface = md_theme_light_onSurface,
    // surfaceVariant: màu cho các surface phụ v nội dung có mức độ nhấn mạnh thấp hơn
    surfaceVariant = md_theme_light_surfaceVariant,
    onSurfaceVariant = md_theme_light_onSurfaceVariant,
    surfaceTint = md_theme_light_surfaceTint,
    inverseSurface = md_theme_light_inverseSurface,
    inverseOnSurface = md_theme_light_inverseOnSurface,
    error = md_theme_light_error,
    onError = md_theme_light_onError,
    errorContainer = md_theme_light_errorContainer,
    onErrorContainer = md_theme_light_onErrorContainer,
    //outlinr
    outline = md_theme_light_outline,
    outlineVariant = md_theme_light_outlineVariant,
    //scrim dùng cho overlay
    scrim = md_theme_light_scrim,
     // surfaceDim: màu nền bị giảm độ sáng
    surfaceDim = md_theme_light_surfaceDim,
    //surfaceBright: màu nền sáng hơn surface dùng cho vùng sáng nổi bật hơn
    surfaceBright = md_theme_light_surfaceBright,
    surfaceContainerLowest = md_theme_light_surfaceContainerLowest,
    surfaceContainerLow = md_theme_light_surfaceContainerLow,
    surfaceContainer = md_theme_light_surfaceContainer,
    surfaceContainerHigh = md_theme_light_surfaceContainerHigh,
    surfaceContainerHighest = md_theme_light_surfaceContainerHighest,
    success = success,
    isLight = true,
    //PhucTH
    primary = md_theme_light_primary,
    onPrimary = md_theme_light_onPrimary,
//    Text
    primaryText = md_theme_light_primary_text,
    secondaryText = md_theme_light_secondary_text,
    //
    disabledColor = md_theme_light_disabled_text,
    //Button
    primaryButtonBackground = md_theme_light_primary_button_background,
    //background là màu background chính
    background = md_theme_light_background,
    onBackground = md_theme_light_onBackground,
    primaryContainer = md_theme_light_primaryContainer,
    onPrimaryContainer = md_theme_light_onPrimaryContainer,
)

//fun darkAppColors(): AppColors = AppColors(
//    primary = md_theme_dark_primary,
//    onPrimary = md_theme_dark_onPrimary,
//    primaryContainer = md_theme_dark_primaryContainer,
//    onPrimaryContainer = md_theme_dark_onPrimaryContainer,
//    inversePrimary = md_theme_dark_inversePrimary,
//    secondary = md_theme_dark_secondary,
//    onSecondary = md_theme_dark_onSecondary,
//    secondaryContainer = md_theme_dark_secondaryContainer,
//    onSecondaryContainer = md_theme_dark_onSecondaryContainer,
//    tertiary = md_theme_dark_tertiary,
//    onTertiary = md_theme_dark_onTertiary,
//    tertiaryContainer = md_theme_dark_tertiaryContainer,
//    onTertiaryContainer = md_theme_dark_onTertiaryContainer,
//    background = md_theme_dark_background,
//    onBackground = md_theme_dark_onBackground,
//    surface = md_theme_dark_surface,
//    onSurface = md_theme_dark_onSurface,
//    surfaceVariant = md_theme_dark_surfaceVariant,
//    onSurfaceVariant = md_theme_dark_onSurfaceVariant,
//    surfaceTint = md_theme_dark_surfaceTint,
//    inverseSurface = md_theme_dark_inverseSurface,
//    inverseOnSurface = md_theme_dark_inverseOnSurface,
//    error = md_theme_dark_error,
//    onError = md_theme_dark_onError,
//    errorContainer = md_theme_dark_errorContainer,
//    onErrorContainer = md_theme_dark_onErrorContainer,
//    outline = md_theme_dark_outline,
//    outlineVariant = md_theme_dark_outlineVariant,
//    scrim = md_theme_dark_scrim,
//    // Defaulting missing dark surface roles to primary surface colors for now
//    surfaceDim = md_theme_dark_surface,
//    surfaceBright = md_theme_dark_surface,
//    surfaceContainerLowest = md_theme_dark_surface,
//    surfaceContainerLow = md_theme_dark_surface,
//    surfaceContainer = md_theme_dark_surface,
//    surfaceContainerHigh = md_theme_dark_surface,
//    surfaceContainerHighest = md_theme_dark_surface,
//    success = success, // Usually would have a dark variant
//    isLight = false,
//    primaryText = md_theme_light_primary_text //Todo change color
//)

fun ColorScheme.toAppColors(isLight: Boolean): AppColors = AppColors(
    primary = primary,
    onPrimary = onPrimary,
    primaryContainer = primaryContainer,
    onPrimaryContainer = onPrimaryContainer,
    inversePrimary = inversePrimary,
    secondary = secondary,
    onSecondary = onSecondary,
    secondaryContainer = secondaryContainer,
    onSecondaryContainer = onSecondaryContainer,
    tertiary = tertiary,
    onTertiary = onTertiary,
    tertiaryContainer = tertiaryContainer,
    onTertiaryContainer = onTertiaryContainer,
    background = background,
    onBackground = onBackground,
    surface = surface,
    onSurface = onSurface,
    surfaceVariant = surfaceVariant,
    onSurfaceVariant = onSurfaceVariant,
    surfaceTint = surfaceTint,
    inverseSurface = inverseSurface,
    inverseOnSurface = inverseOnSurface,
    error = error,
    onError = onError,
    errorContainer = errorContainer,
    onErrorContainer = onErrorContainer,
    outline = outline,
    outlineVariant = outlineVariant,
    scrim = scrim,
    surfaceDim = surfaceDim,
    surfaceBright = surfaceBright,
    surfaceContainerLowest = surfaceContainerLowest,
    surfaceContainerLow = surfaceContainerLow,
    surfaceContainer = surfaceContainer,
    surfaceContainerHigh = surfaceContainerHigh,
    surfaceContainerHighest = surfaceContainerHighest,
    success = success, // Use the constant from Color.kt
    isLight = isLight,
    primaryText = md_theme_light_primary_text,
    primaryButtonBackground = md_theme_light_primary_button_background,
    secondaryText = md_theme_light_secondary_text,
    disabledColor = md_theme_light_disabled_text,
)

fun AppColors.toColorScheme(): ColorScheme = ColorScheme(
    primary = primary,
    onPrimary = onPrimary,
    primaryContainer = primaryContainer,
    onPrimaryContainer = onPrimaryContainer,
    inversePrimary = inversePrimary,
    secondary = secondary,
    onSecondary = onSecondary,
    secondaryContainer = secondaryContainer,
    onSecondaryContainer = onSecondaryContainer,
    tertiary = tertiary,
    onTertiary = onTertiary,
    tertiaryContainer = tertiaryContainer,
    onTertiaryContainer = onTertiaryContainer,
    background = background,
    onBackground = onBackground,
    surface = surface,
    onSurface = onSurface,
    surfaceVariant = surfaceVariant,
    onSurfaceVariant = onSurfaceVariant,
    surfaceTint = surfaceTint,
    inverseSurface = inverseSurface,
    inverseOnSurface = inverseOnSurface,
    error = error,
    onError = onError,
    errorContainer = errorContainer,
    onErrorContainer = onErrorContainer,
    outline = outline,
    outlineVariant = outlineVariant,
    scrim = scrim,
    surfaceDim = surfaceDim,
    surfaceBright = surfaceBright,
    surfaceContainerLowest = surfaceContainerLowest,
    surfaceContainerLow = surfaceContainerLow,
    surfaceContainer = surfaceContainer,
    surfaceContainerHigh = surfaceContainerHigh,
    surfaceContainerHighest = surfaceContainerHighest
)
