package com.vie.mit.common.theme

import androidx.compose.ui.graphics.Color

// Light Theme - Green Mobility
val md_theme_light_primary = Color(0xFF2BB32A) //0xFF006E0A
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFFFFF)
val md_theme_light_onPrimaryContainer = Color(0xFF006E0A)
val md_theme_light_secondary = Color(0xFF526254)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD2E5D2)
val md_theme_light_onSecondaryContainer = Color(0xFF566758)
val md_theme_light_tertiary = Color(0xFFAF265B)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFF6598)
val md_theme_light_onTertiaryContainer = Color(0xFF6A0031)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF93000A)
val md_theme_light_background = Color(0xFFFFFFFF)
val md_theme_light_onBackground = Color(0xFF1A1C1A)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF1A1C1A)
val md_theme_light_surfaceVariant = Color(0xFFE2E3DF)
val md_theme_light_onSurfaceVariant = Color(0xFF3E4A39)
val md_theme_light_outline = Color(0xFF6E7B68)
val md_theme_light_outlineVariant = Color(0xFFBDCBB5)
val md_theme_light_inverseOnSurface = Color(0xFFF1F1ED)
val md_theme_light_inverseSurface = Color(0xFF2F312F)
val md_theme_light_inversePrimary = Color(0xFF5EE153)
val md_theme_light_surfaceTint = Color(0xFF006E0A)
val md_theme_light_scrim = Color(0x66000000)

// New Surface Roles
val md_theme_light_surfaceDim = Color(0xFFF6F6F6)
val md_theme_light_surfaceBright = Color(0xFFFAF9F6)
val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_theme_light_surfaceContainerLow = Color(0xFFF7FAF7)
val md_theme_light_surfaceContainer = Color(0xFFEEEEEA)
val md_theme_light_surfaceContainerHigh = Color(0xFFE8E8E5)
val md_theme_light_surfaceContainerHighest = Color(0xFFE2E3DF)
val md_theme_light_primary_text = Color(0xFF1A1A1A)
val md_theme_light_secondary_text = Color(0xFF6C7278)
val md_theme_light_disabled_text = Color(0xFF6C7278)
val md_theme_light_primary_button_background = Color(0xFF006E0A)

// Fixed Colors
val md_theme_light_primaryFixed = Color(0xFF7BFE6C)
val md_theme_light_primaryFixedDim = Color(0xFF5EE153)
val md_theme_light_onPrimaryFixed = Color(0xFF002201)
val md_theme_light_onPrimaryFixedVariant = Color(0xFF005305)
val md_theme_light_secondaryFixed = Color(0xFFD5E7D5)
val md_theme_light_secondaryFixedDim = Color(0xFFB9CBB9)
val md_theme_light_onSecondaryFixed = Color(0xFF101F13)
val md_theme_light_onSecondaryFixedVariant = Color(0xFF3B4B3D)
val md_theme_light_tertiaryFixed = Color(0xFFFFD9E1)
val md_theme_light_tertiaryFixedDim = Color(0xFFFFB1C4)
val md_theme_light_onTertiaryFixed = Color(0xFF3F001A)
val md_theme_light_onTertiaryFixedVariant = Color(0xFF8E0244)

// Custom Colors
val success = Color(0xFF2BB32A)

// Dark Theme (Keeping existing values for now, but prefixed for consistency)
val md_theme_dark_primary = Color(0xFF7DD99A)
val md_theme_dark_onPrimary = Color(0xFF00391C)
val md_theme_dark_primaryContainer = Color(0xFF00522B)
val md_theme_dark_onPrimaryContainer = Color(0xFF99F6B4)
val md_theme_dark_secondary = Color(0xFFB7CCB8)
val md_theme_dark_onSecondary = Color(0xFF223527)
val md_theme_dark_secondaryContainer = Color(0xFF384B3C)
val md_theme_dark_onSecondaryContainer = Color(0xFFD2E8D3)
val md_theme_dark_tertiary = Color(0xFFA2CED9)
val md_theme_dark_onTertiary = Color(0xFF01363F)
val md_theme_dark_tertiaryContainer = Color(0xFF204D56)
val md_theme_dark_onTertiaryContainer = Color(0xFFBEEAF6)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C19)
val md_theme_dark_onBackground = Color(0xFFE1E3DE)
val md_theme_dark_surface = Color(0xFF191C19)
val md_theme_dark_onSurface = Color(0xFFE1E3DE)
val md_theme_dark_surfaceVariant = Color(0xFF414942)
val md_theme_dark_onSurfaceVariant = Color(0xFFC0C9C0)
val md_theme_dark_outline = Color(0xFF8A938B)
val md_theme_dark_outlineVariant = Color(0xFF414942)
val md_theme_dark_inverseOnSurface = Color(0xFF191C19)
val md_theme_dark_inverseSurface = Color(0xFFE1E3DE)
val md_theme_dark_inversePrimary = Color(0xFF006D3B)
val md_theme_dark_surfaceTint = Color(0xFF7DD99A)
val md_theme_dark_scrim = Color(0xFF000000)
val seed = Color(0xFF006D3B)
